name: Playwright End To End Tests
on:
  push:
      branches:
      - 'feature/e2e'
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.1-noble
    services:
      # Add docker-in-docker service
      docker:
        image: docker:dind
        privileged: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@navikt'
    - name: Install Docker Compose
      run: |
        apt-get update
        apt-get install -y docker-compose-plugin
    - name: Install dependencies
      env:
        NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      run: |
        npm config set @navikt:registry https://npm.pkg.github.com
        npm config set //npm.pkg.github.com/:_authToken $NPM_AUTH_TOKEN
        npm ci --prefer-offline --no-audit --ignore-scripts
    - name: Clone shared docker compose
      run: |
        mkdir -p ..
        git clone https://${{ secrets.READER_TOKEN }}@github.com/navikt/pam-docker-compose-shared.git ../pam-docker-compose-shared
    - name: Start dependencies
      run: |
        # Make sure the script is executable
        chmod +x start-docker-compose.sh
        # Start dependencies in background
        nohup ./start-docker-compose.sh > /dev/null 2>&1 &
        # Wait for services to be ready
        sleep 10
        echo "Dependencies started"
    - name: Build application
      run: npm run build
    - name: Run application
      env:
        NODE_ENV: test
      run: npm run start &
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        HOME: /root
        TEST_BASE_URL: http://localhost:3000
      run: |
        # Wait for the app to be ready
        npx wait-on http://localhost:3000
        npx playwright test e2e
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
